os: Visual Studio 2017
version: 1.2.1.{build}

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  NUGET_XMLDOC_MODE: skip

branches:
  only:
    - master

build_script:
  - ps: .\Build.ps1

after_build:
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "artifacts\code-coverage.xml"

artifacts:
  - path: artifacts\*.nupkg

nuget:
  disable_publish_on_pr: true

skip_tags: false
test: off

deploy:

  - provider: NuGet
    api_key:
      secure: 6MzbzEs4YdJKS67Gio5gEO8mNKmwfC4UHTCmECZ1KOutI6ndm4vAECazmVNB6an7
    artifact: /.*\.nupkg/
    skip_symbols: false
    on:
      appveyor_repo_tag: true
