name: on-push-do-docs

on:
#  push:
#    branches: [ main ]
#    paths-ignore:
#    - '**/*.md'
  workflow_dispatch:

jobs:
  docs:
    name: Update documentation
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3.0.0

    - name: Run MarkdownSnippets
      run: |
        dotnet tool install --global MarkdownSnippets.Tool
        mdsnippets "${GITHUB_WORKSPACE}" --exclude-directories ./artifacts
      shell: bash
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: true
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    - name: Push changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Update documentation\n\nUpdate examples in documentation." -a  || echo "Nothing to commit"
        remote="https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git"
        branch="${GITHUB_REF:11}"
        git push "${remote}" "${branch}" || echo "Nothing to push"
      shell: bash
